In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'


# **Section 1: Creating Arrays**

#### 1. Create a 1D array with 20 random integers between 1 and 100.
**Hint:** Use the `np.random.randint()` function, specifying the range and size.
#### 2. Create a 5x5 matrix where all the border elements are 1, and the inside elements are 0.
#### 3. Create a diagonal matrix with values `[1, 2, 3, 4]` on the diagonal.
#### 4. Create an array of shape (3, 3) where each row contains numbers from 1 to 3.
**Hint:** Use `np.tile()` to repeat arrays along rows or columns.
#### 5. Create a 1D array with alternating 0s and 1s of length 10.
#### 6. Create a 3x3 matrix with random integers between 10 and 20, and set the datatype to `int32`.

In [2]:
#Q1 -

arr = np.random.randint(low=1,high=100,size=[3,3])

arr

array([[13, 78, 48],
       [92, 71, 63],
       [28,  9, 45]])

In [19]:
#Q2 -

arr = np.ones((5,5))
arr[1:4,1:4] = 0

arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
arr = [1,2,3,4]

arr1 = np.diag(arr)
arr1

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# **Section 2: Array Attributes**

####1. Create a NumPy array of shape (4, 5) filled with random integers between 1 and 10. Now use an appropriate attribute of an array and find the following:

  1. shape of the array
  2. size of the array
  3. number of dimensions
  4. data type

####2. Write a Python function that takes an array as input and returns the number of dimensions (ndim) of the array.
Test the function with the following arrays:

  1. A 1D array with 5 elements.
  2. A 2D array of size (3x4).
  3. A 3D array of size (2x3x4).


####3. Create a NumPy array with the elements between 1 to 100 and use the dtype attribute to find out the data type of the elements. Modify the program to create arrays with elements of type float and string, and observe the changes in dtype.

####4. Write a Python function that:
  1. Creates a 6×3 array of integers using NumPy.
  2. Prints the shape of the array using the shape attribute.
  3. Reshapes the array to 3×6 and prints the new shape.



####5. Write a program to:
  1. Create an array of any size with all elements being 0 and use the appropriate attribute to print the size (in bytes) of each element in the array.
  2. Create an array of any size with elements between 1 to 10 and print the size.
  3. Create another array with floating-point numbers of any size and observe how the size changes.



In [23]:
#Q1
arr = np.random.randint(low=1,high=10,size=(4,5))

print(f"Shape of the Array: {arr.shape}")
print(f"Size of the Array: {arr.size}")
print(f"Number of dimensions of the Array: {arr.ndim}")
print(f"Data type of the Array: {arr.dtype}")

Shape of the Array: (4, 5)
Size of the Array: 20
Number of dimensions of the Array: 2
Data type of the Array: int64


In [33]:
#Q4
arr = np.random.randint(low=1,high=10,size=(6,3))
print(arr.shape)

arr = arr.reshape(3,6)
print(arr.shape)

(6, 3)
(3, 6)


# **Section 3: Sorting and Partioning**

####1. Given an array arr, sort the array in ascending order without modifying the original array. Print both the original and sorted arrays.(use np.sort())

####2. You have arr = np.array([50, 30, 40, 20]) and names = np.array(["A", "B", "C", "D"]).
Sort the arr values in ascending order and rearrange the names array accordingly.(use np.argsort() to get sorted indices and reorder names)

####3. Write code to find the k smallest elements from the array arr. Print these elements in ascending order.(use np.partition())

####4. Partition the array arr such that all elements smaller than a particular number(user input) appear before those greater than or equal to that number. Print the partitioned array.(use np.partition() to find the pivot value's index)

####5. Sort each row of a 2D array arr in ascending order.(use np.sort() with axis parameter)

####6. Print k largest elements of an array arr in descending order.(use np.partition() to find top k elements)

####7. Given an array arr(containing possible negative values), sort the array in ascending order based on the absolute values of the elements. Print the sorted array.(use np.argsort() with a custom key for absolute values)

####8. Given an array arr, sort only the elements greater than k in ascending order, keeping the other elements in their original positions.(create a mask to find elements greater than k, use np.sort() to sort them then reassign the sorted values back to their original indices in the array)

In [35]:
#Q1
arr = np.random.randint(1,10,(6,))

sorted_arr = np.sort(arr)
arr, sorted_arr

(array([6, 8, 8, 9, 2, 2]), array([2, 2, 6, 8, 8, 9]))

In [37]:
#Q2
arr = np.array([50,30,40,20])
names = np.array(["A","B","C","D"])


idx = np.argsort(arr)
sorted_arr = arr[idx]
sorted_names = names[idx]

sorted_arr, sorted_names

(array([20, 30, 40, 50]), array(['D', 'B', 'C', 'A'], dtype='<U1'))

# **Section 4: Indexing and slicing**

#### 1. 2D Array Indexing
Consider the following 2D array:
`arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])`
- Access the element at row index 1 and column index 2.
- Extract the first row.
- Extract the last column.

In [44]:
#Q1

arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])


arr_2d[1,2],arr_2d[0,:], arr_2d[:,2]

(np.int64(30), array([ 5, 10, 15]), array([15, 30, 45]))

#### 2. Boolean Indexing
Given an array `arr = np.array([2, 5, 8, 11, 14, 17, 20])`, use boolean indexing to:
- Extract all values greater than 10.
- Replace all values greater than 15 with -1.

In [47]:
arr = np.array([2, 5, 8, 11, 14, 17, 20])

mask = arr > 10

new_arr = arr[mask]

mask2 = new_arr > 15
new_arr[mask2] = -1

new_arr

array([11, 14, -1, -1])

#### 3. Fancy Indexing
Using the 2D array `arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])`, write code to:

- Select the elements at positions (0,2), (1,1), and (2,0).
- Use fancy indexing to create a submatrix with rows 0 and 2, and columns 1 and 2.

- **Hint:**
 - For 1st part, use arrays of row and column indices
 - For 2nd part, you can create a submatrix using fancy indexing by using np.newaxis to match the dimensions


#### 4. Slicing 1D array
Given the array `arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])`, write code to:

- Extract the first 4 elements.
- Extract every second element from the entire array.
- Extract elements from index 2 to the end, stepping by 2.

#### 5. Slicing a 2D Array
Given the following 2D array:
`arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])`
- Slice and print the last two columns of 1st row.
- Slice and print the last row, reversed.

#### 6. Handling Out-of-Range Indices in Slicing vs. Indexing
Given the array:
`arr = np.array([10, 20, 30, 40, 50])`


- What will be the output of the following slicing operations? Explain why they work, even though some indices are out of range.
 - print(arr[2:10])  
 - print(arr[-10:3])    

- Compare the behavior of slicing to accessing a single element with an out-of-range index (e.g., arr[10]). Why does slicing not raise an error in these cases, but indexing does?

#### 7.  Work with an Audio File

Download the audio file from the following link: Simple Logo - Pixabay. Load the audio file using pydub and complete the following tasks:

- Extract the first second of the audio and plot its waveform.
   - Hint: Use the frame rate to calculate how many samples are in 1 second, and use slicing to extract this part.

-   Extract the last second of the audio and plot its waveform.
  

-  Combine the samples from the first second and the last second into a new array and plot the combined waveform.
 - Hint: Use NumPy’s np.concatenate() function to merge the two slices.

# **Section 5: Reshaping in NumPy**


####1. Create a 2D array of shape (3, 5). Flatten it into a 1D array and then reshape it back into a (5, 3) array.

####2. Create a 1D array
```
arr = np.array([1, 2, 3, 4, 5])
```
####Reshape arr into (5,1), then convert to (5,) and then convert it into (1,5).


####3. Create a 1D NumPy array with values ranging from 1 to 100. Reshape it into a (10, 10) matrix. Apply '.ravel()' and '.flatten()' on the matrix and modify the original matrix. Compare the outputs of both methods and explain the difference in memory sharing.


####4. Generate a 5x5 NumPy matrix representing pixel intensities from an image. Use slicing to extract the central 3x3 section of the matrix and flatten it. How does reshaping impact the spatial relationships of the pixels?


####5. Create a 3-channel RGB image as a NumPy array of shape (3, 4, 4) with random integer values between 0 and 255. Flatten the image using '.reshape()' and reshape it back to its original shape. Explain the order of pixel data stored and how reshaping affects the channel structure.



In [52]:
arr = np.random.randint(1,10,(3,5))
arr

new_arr = arr.flatten()

new_arr = new_arr.reshape(5,3)
new_arr

array([[9, 3, 4],
       [9, 4, 1],
       [3, 5, 6],
       [4, 7, 3],
       [7, 3, 9]])

# **Section 6: Universal Functions**

Q1) Given an array x = [1, 4, 9, 16, 25], compute the square root of each element in the array and print the result.

Q2) Create an array angles =[0, $\frac{\pi}{2}$, $\pi$, $\frac{3\pi}{2}$]
, calculate the sine of each angle and print the result.



Q3) Given two arrays a =[True, False, True] and b = [False, False, True], perform an element-wise logical AND operation and print the result.

Q4) Create two arrays x = [1, 2, 3, 4] and y = [2, 2, 3, 5], perform an element-wise comparison (x < y) and print the result.

Q5) Create an array x =[-2, -1, 0, 1, 2, 3, 4], compute the following element-wise operation:

* If an element is negative, square it.
* If an element is non-negative, compute its exponential.
Print the resulting array.

In [57]:
x = [1,4,9,16,25]
x = np.array(x)

x = np.sqrt(x)

In [58]:
x = np.array([0,np.pi/2,np.pi,3*np.pi/2])

y = np.sin(x)
y

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00])

# **Section 7: Aggregations**

####1. Generate a random array of size 10.
 calculate the following:
- Print the array
- The sum of all elements.
- The mean of the array.
- The standard deviation.
- Find 5$*$Minimum -3$*$Maximum

####2. Generate a 4x5 matrix with random integers between 1 and 50.
- Print the matrix.
- Compute the mean of all elements in the matrix.
- Compute the sum of each row in the matrix.

####3. Generate a random 3x3 matrix with random integers between 1 to 10
- Find the minimum value in each column and store it in a separate list min.
- Find the maximum value in each row and store it in a separate list max.
- Find the value of minimum of list max - maximum of list min.

####4. Given the array : data = np.array([15, 25, 35, 45, 55, 65]):
- Find the minimum value.
- Subtract this minimum value from all elements of the array and then calculate the mean of the resulting array.

####5. Given the array : arr = np.array([3, 5, 7, 9, 11]):
- Compute the cumulative sum of the elements.
- Compute the cumulative product of the elements.

####6. Imagine you have a dataset representing the scores of 4 students in 3 subjects:
scores = np.array([[85, 92, 78], [88, 76, 95], [91, 89, 82], [75, 85, 88]])
- Compute the average score for each student.
- Compute the highest score in each subject.
- Determine the overall average score for all students across all subjects.

In [60]:
arr = np.random.randint(1,100,10)

arr,np.sum(arr),np.mean(arr),np.std(arr), 5*np.min(arr)-3*np.max(arr)

(array([88, 56, 52, 99, 53, 27,  2, 77, 10, 43]),
 np.int64(507),
 np.float64(50.7),
 np.float64(30.166372005927396),
 np.int64(-287))

# **Section 8: Broadcasting in NumPy**



####1. Given two arrays:

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) (shape: (3, 3))
B = np.array([10, 20, 30]) (shape: (3,))
Perform elementwise addition of A and B using broadcasting and print the result.

What is the resulting shape?





####2. Write a function check_broadcasting(shape1, shape2) that:

Accepts two shapes as input and checks if they are broadcast-compatible.
Use the function to test the following shape pairs:
(3, 4) and (4,)
(2, 1, 5) and (3, 5)
(2, 3) and (2,)

For each case:

* State whether broadcasting is possible.

* If possible, state the resulting shape of the operation

####3. Create a 2D array A of shape (3, 5) with random integers between 1 and 10.
Create a 1D array B of shape (5,) with random integers between 1 and 5.
Use broadcasting to subtract B from each row of A and print the result.

####4.  Create a 3D array A with shape (2, 4, 3) filled with random integers between 0 and 10.

* Create an array B of shape (4, 3) containing a constant value of 5.
* Use broadcasting to add B to each 2D array slice of A.
* Print the result

####5. : You are given a grayscale image of shape (32, 32), where each pixel value is an integer. You want to apply a scaling factor of 0.5 to all the pixel values using broadcasting.


* Use broadcasting to scale the image by multiplying it with the scaling factor 0.5.
* Verify that the pixel values of the image are halved by printing the scaled image.

####6. Calculate the distance between an observation point and a set of code points (codes). The goal is to find the closest code to the observation by calculating the Euclidean distance between each code and the observation.

* Given two arrays :

codes = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [1.0, 1.0, 1.0],
    [2.0, 3.0, 4.0]
])


observation = np.array([3.0, 3.0, 3.0])


* Use broadcasting to calculate the squared Euclidean distance between the observation and each code.
* Find and print the index of the closest code to the observation.
* Print the distance between the observation and the closest code.

**HINT : use np.argmin() to find the index of the closest code**




In [63]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([10, 20, 30])

C = A+B

print(C)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


# Section 9: Concatenation

1. Write a program to vertically stack arrays using `np.vstack` and print the result: (Use any three 1D arrays) <br/>
<br/>
2. Write a program to horizontally stack arrays using `np.hstack`. Print the result: (Use any three 1D arrays) <br/>
<br/>
3. Given two 2D arrays of the same row size, horizontally stack them using `np.hstack` and print the result:<br/>
`m = np.array([[2, 4], [3, 6]])`<br/>
`n = np.array([[4, 8], [5, 10]])`<br/>
<br/>
4. Using `np.vstack`, stack the following arrays vertically and print the results:<br/>
`a = np.array([11, 12, 13])`<br/>
`b = np.array([[14, 15, 16], [17, 18, 19]])`<br/>
<br/>
5. Concatenate the following 2D arrays along different axes using `np.concatenate`. Demonstrate how to concatenate them along axis 0 and axis 1.<br/>
`x = np.array([[1, 2], [3, 4]])`<br/>
`y = np.array([[5, 6], [7, 8]])`<br/>
`z = np.array([[9, 10], [11, 12]])`<br/>

In [64]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([4,5,6])

np.vstack((x,y,z))

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6]])

# Section 10: Boolean Masking

1. Use Boolean masking to filter elements from a 1D array:
Write a program to create a 1D array and use Boolean masking to filter out all elements greater than 5.<br/>

2. Apply a Boolean mask to a 2D array:
Given the 2D array below, create a Boolean mask to select all elements greater than 10 and print the masked elements.<br/>
`arr = np.array([[5, 12, 18], [7, 1, 3], [11, 6, 14]])`
 <br/>
3. Create a Boolean mask using a condition on an array:
Create a 1D array of integers from 0 to 10. Use a Boolean mask to filter out all even numbers and print the result.<br/>
Example:
`arr = np.arange(11)`
<br/>
4. Combine Boolean masks using logical operations:
Given the array below, create and combine two Boolean masks:<br/>
One mask selects elements greater than 5.
The other mask selects elements divisible by 3.
Combine the masks using logical AND and print the result.
Example:
`arr = np.array([1, 3, 6, 9, 12, 15])`
<br/>
5. Mask elements in a 2D array and replace them:
Write a program to replace all elements less than 5 in the 2D array below with 0 using Boolean masking.
<br/>
6.  Count elements satisfying a condition using Boolean masks:
Write a program to count how many elements in the array below are greater than 5.
<br/>

In [67]:
arr = np.random.randint(1,10,20)

mask = arr > 5

new_arr = arr[mask]

arr, new_arr

(array([4, 1, 2, 7, 6, 3, 1, 5, 7, 9, 9, 6, 5, 1, 8, 4, 4, 8, 9, 9]),
 array([7, 6, 7, 9, 9, 6, 8, 8, 9, 9]))

In [70]:
arr = np.random.randint(1,10,20)

mask = arr > 5


arr, arr[mask], np.sum(mask)

(array([2, 2, 7, 8, 1, 9, 6, 2, 1, 1, 2, 6, 8, 2, 5, 1, 6, 4, 3, 7]),
 array([7, 8, 9, 6, 6, 8, 6, 7]),
 np.int64(8))